name: knime-lwreg
channels:
  - knime
  - conda-forge
dependencies:
  - python=3.11
  - knime-extension
  - knime-python-base
  
  # For lwreg
  - rdkit >=2023.03.1
  - ipython
  - jupyter
  - ipython-sql
  - sqlalchemy=1.4
  - pytest
  - tqdm
  - click
  - pip
  - pip:
    - "git+https://github.com/rinikerlab/lightweight-registration"